name: ML Deployment Pipeline

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  workflow_dispatch:


env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  REPOSITORY: ml-api

jobs:

# ---------- BUILD IMAGE ----------
  build:
    runs-on: ubuntu-latest

    outputs:
      image: ${{ steps.image.outputs.image }}

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - run: gcloud auth configure-docker $REGION-docker.pkg.dev

      - id: image
        run: |
          IMAGE=$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/ml-api:${{ github.sha }}
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "image=$IMAGE" >> $GITHUB_OUTPUT


# ---------- DEV DEPLOY ----------
  deploy-dev:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - run: gcloud run deploy ml-api-dev --image "${{ needs.build.outputs.image }}" --region "${{ env.REGION }}" --platform managed --allow-unauthenticated




# ---------- TEST DEPLOY ----------
  deploy-test:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - run: gcloud run deploy ml-api-test --image "${{ needs.build.outputs.image }}" --region "${{ env.REGION }}" --platform managed --allow-unauthenticated




# ---------- STAGING ----------
  deploy-stg:
    needs: deploy-test
    runs-on: ubuntu-latest

    steps:
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      
      - run: gcloud run deploy ml-api-stg --image "${{ needs.build.outputs.image }}" --region "${{ env.REGION }}" --platform managed --allow-unauthenticated


# ---------- PRODUCTION ----------
  deploy-prod:
    needs: deploy-stg
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
     
      - run: gcloud run deploy ml-api-prod --image "${{ needs.build.outputs.image }}" --region "${{ env.REGION }}" --platform managed --allow-unauthenticated

